# Gradle properties
org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
kotlin.stdlib.default.dependency=false
kotlin.code.style=official

# Plugin Properties
pluginGroup=com.davidmszrs.horizonjetbrains
pluginName=New Horizon
pluginVersion=3.0.8
pluginSinceBuild=241.0
pluginUntilBuild=253.*

# IntelliJ Platform Properties
platformType=IC
platformVersion=2024.1.7
platformPlugins=
platformBundledPlugins=com.intellij.java,org.jetbrains.kotlin

# Gradle Version
gradleVersion=8.14